server:
  port: 8080
  tomcat:
    max-http-form-post-size: 5GB
    connection-timeout: 43200000
    max-keep-alive-requests: -1
    keep-alive-timeout: 43200000

  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB
      file-size-threshold: 2MB
  datasource:
    url: jdbc:h2:~/rhoonart-db;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.security.web.access: TRACE
    org.springframework.security.web.context: TRACE
    org.springframework.batch: DEBUG
